package com.dequeue.settlement.entity;

import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a completed or in-progress settlement batch for a vendor.
 *
 * <p>A settlement batch covers all eligible completed orders in a defined
 * date range. Once created with status = SETTLED, no further mutation should
 * occur on the financial fields.</p>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "vendor_settlements")
public class VendorSettlement {

    @Id
    private String id;

    /**
     * Human-readable settlement reference, e.g. "SET-2026-0087".
     * Generated by the settlement service before saving.
     */
    @Indexed(unique = true)
    private String settlementRef;

    /** The vendor this settlement belongs to. */
    @Indexed
    private String vendorId;

    // ── Period ───────────────────────────────────────────────────────────────

    private LocalDate periodFrom;
    private LocalDate periodTo;

    // ── Order summary ─────────────────────────────────────────────────────────

    /** IDs of all PaymentTransaction records included in this settlement. */
    @Builder.Default
    private List<String> transactionIds = new ArrayList<>();

    /** Total number of orders included. */
    @Builder.Default
    private int orderCount = 0;

    // ── Revenue breakdown ─────────────────────────────────────────────────────

    /** Sum of amounts for Cashfree transactions. */
    @Builder.Default
    private BigDecimal cashfreeSales = BigDecimal.ZERO;

    /** Sum of amounts for Cash/Offline transactions. */
    @Builder.Default
    private BigDecimal offlineSales = BigDecimal.ZERO;

    /** cashfreeSales + offlineSales */
    @Builder.Default
    private BigDecimal totalSales = BigDecimal.ZERO;

    // ── Deductions ────────────────────────────────────────────────────────────

    /** Total Cashfree gateway fees across all Cashfree transactions. */
    @Builder.Default
    private BigDecimal totalCashfreeFees = BigDecimal.ZERO;

    /** Total Cashfree GST/tax across all Cashfree transactions. */
    @Builder.Default
    private BigDecimal totalCashfreeTax = BigDecimal.ZERO;

    /** Total DeQueue platform commission across all transactions. */
    @Builder.Default
    private BigDecimal totalPlatformCharges = BigDecimal.ZERO;

    /** Total refunds applied. */
    @Builder.Default
    private BigDecimal totalRefunds = BigDecimal.ZERO;

    // ── Net ───────────────────────────────────────────────────────────────────

    /**
     * Net amount disbursed / due to vendor:
     *   totalSales − totalCashfreeFees − totalCashfreeTax − totalPlatformCharges − totalRefunds
     */
    @Builder.Default
    private BigDecimal netSettlementAmount = BigDecimal.ZERO;

    // ── Status ────────────────────────────────────────────────────────────────

    @Builder.Default
    private SettlementStatus settlementStatus = SettlementStatus.PENDING;

    /** When this settlement was actually paid out to the vendor. */
    private Instant settledAt;

    /** Notes from the platform admin who processed the settlement. */
    private String adminNotes;

    /** Staff / system that created this settlement record. */
    private String createdBy;

    @CreatedDate
    private Instant createdAt;

    @LastModifiedDate
    private Instant updatedAt;
}
