package com.dequeue.staff.entity;

public enum Permission {
    VIEW_DASHBOARD, MANAGE_ORDERS, MANAGE_MENU, MANAGE_STAFF,
    MANAGE_SETTINGS, VIEW_REPORTS, MANAGE_QUEUE, VIEW_QUEUE,
    UPDATE_ORDER_STATUS, MARK_COLLECTED, MANAGE_DEPARTMENTS,
    MANAGE_PROFILE, MANAGE_QR
}
